### ISSUE TITLE
dotnet core 3.0 preview shows with transparent background

### ISSUE THREAD

**Issue by Dirkster99** [Dirkster99/UserNotifications#2]
The test project in the 
https://github.com/Dirkster99/UserNotifications/tree/NetCoreMultiTargeting

branch compiles with dotnet core 3.0 (daily build) and runs, but the background
of the pop-up window is transparent
![dotnet-issue](https://user-images.githubusercontent.com/2129700/51268608-d6d1ce00-19c0-11e9-8868-52c03720615c.png)

The background in the latest relaese and current build is as expected:
![asitshouldbe release_v1_3_2](https://user-images.githubusercontent.com/2129700/51268836-37610b00-19c1-11e9-87dd-5e38c5fbc7e9.png)

**Comment by Dirkster99** [comment]
[Release_v1_3_2.zip](https://github.com/Dirkster99/UserNotifications/files/2765478/Release_v1_3_2.zip)

**Comment by virzak** [comment]
#3 fixes the issue

**Comment by Dirkster99** [comment]
Issue fixed - thanks - so the lesson learned is that we have to watch:
- for resources not being left behind and
- resource mechanisms like ThemeInfo being transferred correctly

I have seen that the dotnet pack command is using project properties from the UserNotification.csproj file. I wonder if its also possible to use a *.nuspec file to do the packaging for NuGet because it also requires information like licensing and relase notes that are probably not part of the project file properties(?).

My problem is just that I use a command like this:
dotnet pack -c Release UserNotification\UserNotification.csproj  /p:NuspecFile=UserNotifications.nuspec

with this nuspec file: 
[UserNotifications.nuspec.txt](https://github.com/Dirkster99/UserNotifications/files/2769993/UserNotifications.nuspec.txt)

which returns tons of warnings about assembly parts not being included - so I went for the normal manual nuspec creation and published this on NuGet - forgot to check the PreRelease checkbox but I think its fine because we now know it works and I'll be looking at this tomorrow too - probably confirming it works with nuget and removing the alpha part and moving on to the InplaceEditTextBoxLib ...

**Comment by virzak** [comment]
Awesome! Glad that was figured out.
